spring:
  main:
    banner-mode: off
  cache:
    type: none
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5433/a2b?currentSchema=a2b"
    username: "postgres"
    password: "postgres"
    hikari:
      pool-name: "hikari-pool"
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: "a2b"

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-components: never
      show-details: never
      group:
        readiness:
          include: readinessState, db
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "*"
  metrics.export.prometheus.enabled: true

logging.level:
  ROOT: info
  by.vk.springbootweb: info
  org.springframework: info