version: '3.8'
services:

  postgres-a2b:
    image: fragaly/postgres-a2b:1.0.0
    container_name: postgres-a2b
    hostname: postgres-a2b
    restart: on-failure
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=a2b
    ports:
      - "5432:5432"

  service-a2b:
    image: quarkus-reactive-distroless:latest
    container_name: service-a2b
    hostname: service-a2b
    security_opt:
      - seccomp=unconfined
    restart: on-failure
    ports:
      - "8080:8080"