version: '3.8'
services:

  postgres-a2b:
    image: fragaly/postgres-a2b:1.0.0
    container_name: postgres-a2b
    hostname: postgres-a2b
    restart: on-failure
    volumes:
      - data:/var/lib/postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=a2b
    ports:
      - "5432:5432"

  service-a2b:
    image: a2b-service:quarkus-reactive
    container_name: a2b-service
    hostname: a2b-service
    security_opt:
      - seccomp=unconfined
    volumes:
      - data:/var/lib/a2b-service
    restart: on-failure
    ports:
      - "8080:8080"

volumes:
  data: