# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/spring-boot-web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: gradle
    directory: "/spring-boot-web-native"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: gradle
    directory: "/spring-boot-reactive"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: gradle
    directory: "/spring-boot-reactive-native"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: gradle
    directory: "/quarkus-web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: gradle
    directory: "/gatling"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: gradle
    directory: "/datagen"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
