version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/datagen"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: "gradle"
    directory: "/gatling"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: "gradle"
    directory: "/micronaut-reactive"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: "gradle"
    directory: "/quarkus-reactive"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: "gradle"
    directory: "/spring-boot-reactive"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: "gradle"
    directory: "/spring-boot-reactive-native"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: "gradle"
    directory: "/spring-boot-web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: "gradle"
    directory: "/spring-boot-web-native"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: "gradle"
    directory: "/vertx-reactive"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
