# These are supported funding model platforms

TON: [ EQB3lxe8IlUGocilOCzuFhALm71XElZjcyJoFl08Tupx6lfe ] or using DNS [vadzimkavalkou]
BTC: [ 35ruuFbGjjsh4fed32hZKTAaLzVb3q7KjX ]
ETH: [ 0x7a19d2e4e978e473f3c3d762d097f94e8a546eef ]
