server:
  compression:
    enabled: true
  tomcat:
    threads:
      max: 32
      min-spare: 4

spring:
  main:
    banner-mode: off
  cache:
    type: none
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://postgres-a2b:5432/a2b?currentSchema=a2b" #for local solution replace 'postgres-a2b' with localhost and port '5432' to '5433'
    username: "postgres"
    password: "postgres"
    hikari:
      minimumIdle: 4 # default: same as maximumPoolSize
      maximumPoolSize: 8 # cores * 2; default is 10
      connection-timeout: 35000 #default 30000
      pool-name: "hikari-pool"
      idle-timeout: 10000 # default: 600000 (10 minutes)
      max-lifetime: 35000 # default: 1800000 (30 minutes)
      keepaliveTime: 30000 # default: 0 (disabled)
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false
        default_schema: "a2b"
        types:
          print:
            banner: false

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-components: never
      show-details: never
      group:
        readiness:
          include: readinessState, db
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "*"
  metrics.export.prometheus.enabled: true

logging.level:
  ROOT: info
  by.vk.springbootwebnative: info
  org.springframework: info