version: '3.8'
services:

  postgres-a2b:
    image: fragaly/postgres-a2b:1.0.0
    container_name: postgres-a2b
    hostname: postgres-a2b
    restart: on-failure
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=a2b
    ports:
      - "5433:5432"

  service-a2b:
    image: spring-boot-web-native:0.0.1-SNAPSHOT
    container_name: service-a2b
    hostname: service-a2b
    depends_on: 
      - postgres-a2b
    ports:
      - "8080:8080"