quarkus:
  banner:
    enabled: false
  cache:
    enabled: false
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    reactive:
      url: postgresql://localhost:5433/a2b?currentSchema=a2b
#  buildpack:
#    jvm-builder-image:
#    native-builder-image:
#  jib:
#    base-jvm-image:
#    base-native-image:
