version: '3.8'
services:

  postgres-a2b:
    image: fragaly/postgres-a2b:1.0.0
    container_name: postgres-a2b
    hostname: postgres-a2b
    restart: on-failure
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=a2b
    ports:
      - "5433:5432"

  service-a2b:
    image: reactive-service-a2b
    container_name: reactive-service-a2b
    hostname: reactive-service-a2b
    restart: on-failure
    ports:
      - "8080:8080"