### GET ALL COUNTRIES
GET {{scheme}}{{host}}:{{port}}{{context}}/countries

### GET ALL COUNTRY CITIES
GET {{scheme}}{{host}}:{{port}}{{context}}/countries/1/cities

### GET ALL CITY LOCATIONS
GET {{scheme}}{{host}}:{{port}}{{context}}/countries/1/cities/1/locations

### GET USER'S INFO
GET {{scheme}}{{host}}:{{port}}{{context}}/users/11

### UPDATE USER'S INFO
PUT {{scheme}}{{host}}:{{port}}{{context}}/users/11
Content-Type: application/json

{
  "firstName": "Vadzim",
  "lastName": "Kavalkou"
}

### GET USER'S INFO
GET {{scheme}}{{host}}:{{port}}{{context}}/users/11

### GET USER'S TRANSFERS
GET {{scheme}}{{host}}:{{port}}{{context}}/users/11/transfers

### GET USER'S TRANSFER
GET {{scheme}}{{host}}:{{port}}{{context}}/users/11/transfers/1676

### CREATE A TRANSFER FOR USER
POST http://${host}:${port}/api/v1/users/513/transfers/2671
Content-Type: application/json

{
  "description": "Oh my!"
}

### UPDATE USER'S TRANSFER
PUT http://${host}:${port}/api/v1/users/513/transfers/2671
Content-Type: application/json

{
  "description": "WTF",
  "state": "CANCELED"
}