version: '3.8'
services:

  postgres-a2b:
    image: fragaly/postgres-a2b:1.0.0
    container_name: postgres-a2b
    hostname: postgres-a2b
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=a2b
    ports:
      - "5433:5432"
    restart: always

  service-a2b:
    image: a2b-service:spring-boot-web
    container_name: a2b-service
    hostname: a2b-service
    security_opt:
      - seccomp=unconfined
    volumes:
      - data:/var/lib/a2b-service
    restart: on-failure
    ports:
      - "8080:8080"
