# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  schedule:
    - cron: '0 0 1 * *' # every 1st day of month
#  push:
#    branches: [ "main" ]

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon compileJava -q

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon -x test -q

  build:
    runs-on: ubuntu-latest
    needs: [ "compile", "tests" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon build -x check -q

  delivery:
    runs-on: ubuntu-latest
    needs: [ "build" ]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon jib -x check -q -Djib.to.auth.username=${{ secrets.GH_USER }} -Djib.to.auth.password=${{ secrets.GH_TOKEN }}
