name: SPRING BOOT REACTIVE

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**"
      - "spring-boot-reactive/src/**"
      - "spring-boot-reactive/gradle/**"
      - "spring-boot-reactive/docker/**"
      - "spring-boot-reactive/static/**"
      - "spring-boot-reactive/build.gradle.kts"
      - "spring-boot-reactive/settings.gradle.kts"

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon compileJava -q

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon -x test -q

  build:
    runs-on: ubuntu-latest
    needs: [ "compile", "tests" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon build -x check -q

  delivery:
    runs-on: ubuntu-latest
    needs: [ "build" ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: current
      - run: ./gradlew --parallel --no-daemon jib -x check -q -Djib.to.auth.username=${{ secrets.GH_USER }} -Djib.to.auth.password=${{ secrets.GH_TOKEN }}
